# GitHub Pages Configuration for FedCast
title: FedCast
description: Federated Learning for Time Series Forecasting
url: "https://nkdataconv.github.io"
baseurl: "/FedCast"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
remote_theme: jekyll/minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files
include:
  - _pages

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"

# Social links
github_username: NKDataConv
twitter_username: 

# Author information
author:
  name: FedCast Team
  email: nk@data-convolution.de

# Site settings
show_excerpts: true
paginate: 5
paginate_path: "/page:num/"

# SEO
lang: en
timezone: UTC
